version: 2

run:
  timeout: 5m

linters:
  enable:
    - gosec
    - goconst
    - gocritic
    - bodyclose
    - unconvert
    - unparam
    - unused
    - durationcheck
    - makezero
    - nilerr
    - reassign
    - copyloopvar
    - staticcheck

formatters:
  enable:
    - gofumpt
