name: Checks

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.1'
      - name: Build
        run: make build
      - name: ModTidy check
        run: make check-modtidy
      - name: Lint check
        run: |
          make install-lint
          make lint
